# Test: Job Control
# Target: tests/matrix/tests/job_control.sh
#
# Job Control is the magical feature that allows users to seamlessly
# suspend, resume, and manage multiple processes running on a single TTY.
# To properly test this, we must run the target shell under our Rust
# Pseudo-TTY wrapper to trick it into thinking it owns a real terminal.

. "$MATRIX_DIR/lib.sh"


# ==============================================================================
# The Maestro: Managing Processes
# ==============================================================================
# REQUIREMENT: SHALL-2-11-090: Job Control: Job control is a facility that
# allows users to selectively stop (suspend) the execution of processes...
# REQUIREMENT: SHALL-ASYNCHRONOUS EVENTS-025: The sh utility shall take the
# standard action for all signals...
# REQUIREMENT: SHALL-2-11-425: If the shell has a controlling terminal and it
# is the controlling process for the terminal session...
# REQUIREMENT: SHALL-2-11-426: Otherwise, if it has a controlling terminal, it
# shall initially perform the following steps if inter...
# REQUIREMENT: SHALL-2-11-427: If its process group is the foreground process
# group associated with the terminal, the shell shall s...
# REQUIREMENT: SHALL-2-11-428: If its process group is not the foreground
# process group associated with the terminal...
# REQUIREMENT: SHALL-2-11-429: If it is stopped, then when it continues
# execution (after receiving a SIGCONT signal) it shall repea...
# REQUIREMENT: SHALL-2-11-430: Subsequently, the shell shall change the
# foreground process group associated with its controlling te...
# REQUIREMENT: SHALL-2-11-431: When job control is enabled, the shell shall
# create one or more jobs when it executes a list...
# REQUIREMENT: SHALL-2-11-432: For the purposes of job control, a list that
# includes more than one asynchronous AND-OR list shall b...
# REQUIREMENT: SHALL-2-11-433: When a job consisting of a single asynchronous
# AND-OR list is created, it shall form a background jo...
# REQUIREMENT: SHALL-2-11-434: For a list consisting of one or more sequentially
# executed AND-OR lists followed by at most one asyn...
# REQUIREMENT: SHALL-2-11-435: For each pipeline in a foreground job, if the
# pipeline is executed while the list is still a foregro...
# REQUIREMENT: SHALL-2-11-436: A background job that was created on execution
# of an asynchronous AND-OR list can be brought into th...
# REQUIREMENT: SHALL-2-11-437: If a process that the shell subsequently waits
# for is part of this foreground job and is stopped by ...
# REQUIREMENT: SHALL-2-11-438: When a foreground job is created, or a background
# job is brought into the foreground by the fg utili...
# REQUIREMENT: SHALL-2-11-439: If the job was originally created as a background
# job, the foreground process group ID shall be set ...
# REQUIREMENT: SHALL-2-11-440: If the job was originally created as a foreground
# job, the foreground process group ID shall be set ...
# REQUIREMENT: SHALL-2-11-441: If all of the commands in the pipeline are being
# executed by the shell itself in the current shell e...
# REQUIREMENT: SHALL-2-11-442: When a foreground job terminates, or becomes a
# suspended job (see below), if the shell has a control...
# REQUIREMENT: SHALL-2-11-443: Each background job (whether suspended or not)
# shall have associated with it a job number and a proc...
# REQUIREMENT: SHALL-2-11-444: When a background job is brought into the
# foreground by means of the fg utility, the associated job ...
# REQUIREMENT: SHALL-2-11-445: If the currently executing AND-OR list within
# the list comprising the foreground job consists of a s...
# REQUIREMENT: SHALL-2-11-446: Otherwise, the shell shall create a suspended
# job consisting of a set of commands, from within the l...
# REQUIREMENT: SHALL-2-11-447: Commands in the foreground job that have not
# already completed and are not included in the suspended...
# REQUIREMENT: SHALL-2-11-448: If a process that the shell is waiting for is
# part of a foreground job that was started as a foregro...
# REQUIREMENT: SHALL-2-11-449: When a suspended job is created as a result of a
# foreground job being stopped, it shall be assigned ...
# REQUIREMENT: SHALL-2-11-450: The message may indicate that the commands
# comprising the job include commands that have already com...
# REQUIREMENT: SHALL-2-11-451: If the shell is interactive, it shall save the
# terminal settings before changing them to the setting...
# REQUIREMENT: SHALL-2-11-452: When a process associated with a background job
# is stopped by a SIGSTOP, SIGTSTP, SIGTTIN, or SIGTTO...
# REQUIREMENT: SHALL-2-11-453: If set -b is enabled, the message shall be
# written either immediately after the job became suspended...
# REQUIREMENT: SHALL-2-11-454: If set -b is disabled, the message shall be
# written immediately prior to writing the next prompt for...
# REQUIREMENT: SHALL-ASYNCHRONOUS EVENTS-026: If the shell is interactive,
# SIGINT signals received during command line editing shall be handled...
# REQUIREMENT: SHALL-ASYNCHRONOUS EVENTS-027: SIGQUIT and SIGTERM signals shall
# be ignored....
# REQUIREMENT: SHALL-ASYNCHRONOUS EVENTS-028: If the -m option is in effect,
# SIGTTIN, SIGTTOU, and SIGTSTP signals shall be ignored....
# REQUIREMENT: SHALL-ASYNCHRONOUS EVENTS-029: If they are caught, the shell
# shall, in the signal-catching function, set the signal to the default...

# Our test simulates a user starting a background process and then
# interrogating the shell using the `jobs` command. A compliant shell
# should track background processes, and return their state and PID
# back to the user on demand.

interactive_script=$(cat << 'EOF'
sleep 0.5
echo 'sleep 10 &'
sleep 0.5
echo 'jobs'
sleep 0.5
echo 'exit'
EOF
)

# We spin up the PTY tool and run the target shell in interactive mode.
cmd="( $interactive_script ) | \"$MATRIX_DIR/pty\" $TARGET_SHELL -i"

# We run the command and capture raw output from the PTY session.
actual=$(eval "$cmd" 2>&1)

# Does the output from `jobs` reflect the background process? We look for
# the job number `[1]`, the command name `sleep 10`, and its status.
case "$actual" in
    *"[1]"*"Running"*"sleep 10"* | \
    *"[1]"*"sleep 10"* | \
    *"[1]"*"+"*"Running"*"sleep 10"*)
        pass
        ;;
    *)
        fail "Expected 'jobs' command to show background job, got: $actual"
        ;;
esac


# ==============================================================================
# Job Control Subsystem
# ==============================================================================
# REQUIREMENT: SHALL-Command History List-031: When the sh utility is being used
# interactively, it shall maintain a list of commands previously ent...
# REQUIREMENT: SHALL-RATIONALE-616: A user shall explicitly exit to leave the
# interactive shell....
# REQUIREMENT: SHALL-2-11-455: The fg and bg utilities shall send a SIGCONT
# signal to the process group of the process(es) whose st...
# REQUIREMENT: SHALL-2-11-456: If the shell has a controlling terminal, the fg
# utility shall send the SIGCONT signal after it has s...
# REQUIREMENT: SHALL-2-11-457: If the fg utility is used from an interactive
# shell to bring into the foreground a suspended job tha...
# REQUIREMENT: SHALL-2-11-458: When a background job completes or is
# terminated by a signal, an interactive shell shall write a mes...
# REQUIREMENT: SHALL-2-11-459: If set -b is enabled, the message shall be
# written immediately after the job completes or is termina...
# REQUIREMENT: SHALL-2-11-460: If set -b is disabled, the message shall be
# written immediately prior to writing the next prompt for...
# REQUIREMENT: SHALL-2-12-461: If job control is disabled (see the description
# of set -m) when the shell executes an asynchronous A...
# REQUIREMENT: SHALL-2-12-462: In all other cases, commands executed by the
# shell shall inherit the same signal actions as those in...
# REQUIREMENT: SHALL-2-12-463: When a signal for which a trap has been set is
# received while the shell is waiting for the completio...
# REQUIREMENT: SHALL-2-12-464: When the shell is waiting, by means of the wait
# utility, for asynchronous commands to complete, the ...
# REQUIREMENT: SHALL-2-13-465: Utilities other than the special built-ins
# (see 2.15 Special Built-In Utilities) shall be invoked in...
# REQUIREMENT: SHALL-2-13-466: The initial value of these objects shall be the
# same as that for the parent shell, except as noted b...
# REQUIREMENT: SHALL-2-13-467: If the utility is a shell script, traps caught
# by the shell shall be set to the default values and t...
# REQUIREMENT: SHALL-2-13-468: Variables with the export attribute, along with
# those explicitly exported for the duration of the co...
# REQUIREMENT: SHALL-2-13-471: Unless specified otherwise (see trap), traps
# that are not being ignored shall be set to the default ...
# REQUIREMENT: SHALL-2-13-472: If the shell is interactive, the subshell shall
# behave as a non-interactive shell in all respects ex...
# REQUIREMENT: SHALL-2-15-506: The following "special built-in" utilities shall
# be supported in the shell command language....
# REQUIREMENT: SHALL-2-15-507: The output of each command, if any, shall be
# written to standard output, subject to the normal redir...
# REQUIREMENT: SHALL-2-15-508: An error in a special built-in utility may cause
# a shell executing that utility to abort, while an e...
# REQUIREMENT: SHALL-2-15-509: (See 2.8.1 Consequences of Shell Errors for the
# consequences of errors on interactive and non-intera...
# REQUIREMENT: SHALL-2-15-510: As described in 2.9.1 Simple Commands, variable
# assignments preceding the invocation of a special bu...
# REQUIREMENT: SHALL-2-15-511: For those that are not, the requirement in 1.4
# Utility Description Defaults that "--" be recognized ...

report
