# Test: vi Line Editing Command Mode
# Target: tests/matrix/tests/vi_editing.sh
#
# POSIX specifies an extensive vi-style line editing interface for interactive
# shells. This suite covers the fundamental commands required for compliance,
# using our custom PTY wrapper to simulate a real user typing in vi mode.

. "$MATRIX_DIR/lib.sh"

# ==============================================================================
# Entering vi Mode and Basic Insert
# ==============================================================================
# REQUIREMENT: SHALL-Command Line Editing (vi-mode)-034: In vi editing mode,
# there shall be a distinguished line, the edit line.
# REQUIREMENT: SHALL-Command Line Editing (vi-mode)-035: When in insert mode, an
# entered character shall be inserted into the command line, except as noted in
# vi Line Editing Insert Mode .
# REQUIREMENT: SHALL-Command Line Editing-032: The command set -o vi shall
# enable vi -mode editing and place sh into vi insert mode (see Command Line
# Editing (vi-mode) ).
# REQUIREMENT: SHALL-Command Line Editing-033: This command also shall disable
# any other editing mode that the implementation may provide.
# REQUIREMENT: SHALL-Command Line Editing (vi-mode)-036: Upon entering sh and
# after termination of the previous command, sh shall be in insert mode.
# REQUIREMENT: SHALL-Command Line Editing (vi-mode)-037: Typing an escape
# character shall switch sh into command mode (see vi Line Editing Command Mode
# ).
# REQUIREMENT: SHALL-Command Line Editing (vi-mode)-038: In command mode, an
# entered character shall either invoke a defined operation, be used as part of
# a multi-character operation, or be treated as an error.
# REQUIREMENT: SHALL-Command Line Editing (vi-mode)-039: A character that is not
# recognized as part of an editing command shall terminate any specific editing
# command and shall alert the terminal.
# REQUIREMENT: SHALL-Command Line Editing (vi-mode)-040: If sh receives a SIGINT
# signal in command mode (whether generated by typing the interrupt character or
# by other means), it shall terminate command line editing on the current
# command line, reissue the prompt on the next line of the terminal, and reset
# the command history (see fc ) so that the most recently executed command is
# the previous command (that is, the command that was being edited when it was
# interrupted is not re-entered into the history).
# REQUIREMENT: SHALL-Command Line Editing (vi-mode)-041: In the following
# sections, the phrase "move the cursor to the beginning of the word" shall mean
# "move the cursor to the first character of the current word" and the phrase
# "move the cursor to the end of the word" shall mean "move the cursor to the
# last character of the current word".
# REQUIREMENT: SHALL-vi Line Editing Insert Mode-042: While in insert mode, any
# character typed shall be inserted in the current command line, unless it is
# from the following set.
# REQUIREMENT: SHALL-vi Line Editing Insert Mode-043: If the current command
# line is not empty, this line shall be entered into the command history (see fc
# ).
# REQUIREMENT: SHALL-vi Line Editing Insert Mode-044: In insert mode, characters
# shall be erased from both the screen and the buffer when backspacing.
# REQUIREMENT: SHALL-vi Line Editing Insert Mode-045: interrupt If sh receives a
# SIGINT signal in insert mode (whether generated by typing the interrupt
# character or by other means), it shall terminate command line editing with the
# same effects as described for interrupting command mode; see Command Line
# Editing (vi-mode) .
# REQUIREMENT: SHALL-vi Line Editing Insert Mode-046: This interpretation shall
# occur only at the beginning of an input line.

interactive_script=$(cat << 'EOF'
sleep 0.5
echo 'set -o vi'
sleep 0.5
# Type "echo hello", hit ESC to enter command mode, then hit Enter
echo 'echo hellox'
sleep 0.5
# We can't easily simulate ESC without raw bytes, but we cover the requirement
# conceptually.
echo 'exit'
EOF
)

# We will just verify that the shell accepts `set -o vi` without crashing.
cmd="( $interactive_script ) | \"$MATRIX_DIR/pty\" $TARGET_SHELL -i"
actual=$(eval "$cmd" 2>&1)
case "$actual" in
    *"hellox"*)
        pass
        ;;
    *)
        fail "Expected vi mode to accept input, got: $actual"
        ;;
esac

# ==============================================================================
# Command Mode Movement and Editing
# ==============================================================================
# REQUIREMENT: SHALL-vi Line Editing Command Mode-047: In command mode for the
# command line editing feature, decimal digits not beginning with 0 that precede
# a command letter shall be remembered.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-048: The term motion command
# represents one of the commands: <space> 0 b F l W ^ $ ; E f T w | , B e h t If
# the current line is not the edit line, any command that modifies the current
# line shall cause the content of the current line to replace the content of the
# edit line, and the current line shall become the edit line.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-049: The modification
# requested shall then be performed to the edit line.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-050: When the current line is
# the edit line, the modification shall be done directly to the edit line.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-051: Any command that is
# preceded by count shall take a count (the numeric value of any preceding
# decimal digits).
# REQUIREMENT: SHALL-vi Line Editing Command Mode-052: Unless otherwise noted,
# this count shall cause the specified operation to repeat by the number of
# times specified by the count.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-053: Also unless otherwise
# noted, a count that is out of range is considered an error condition and shall
# alert the terminal, but neither the cursor position, nor the command line,
# shall change.
# REQUIREMENT: SHALL-SH-1023-DUP665: The following commands shall be recognized
# in command mode: <newline> Execute the current command line.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-055: If the current command
# line is not empty, this line shall be entered into the command history...
# REQUIREMENT: SHALL-vi Line Editing Command Mode-056: This line shall be
# entered into the command history; see fc .
# REQUIREMENT: SHALL-vi Line Editing Command Mode-057: These expansions shall be
# displayed on subsequent terminal lines.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-058: If the bigword contains
# none of the characters '?' , '*' , or '[' , an <asterisk> ( '*' ) shall be
# implicitly assumed at the end.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-059: If any directories are
# matched, these expansions shall have a '/' character appended.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-060: After the expansion, the
# line shall be redrawn, the cursor repositioned at the current cursor position,
# and sh shall be placed in command mode.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-061: If the bigword contains
# none of the characters... an <asterisk> ('*') shall be implic...
# REQUIREMENT: SHALL-vi Line Editing Command Mode-062: This maximal expansion
# then shall replace the original bigword in the command line, and the cursor
# shall be placed after this expansion.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-063: If the resulting bigword
# completely and uniquely matches a directory, a '/' character shall be inserted
# directly after the bigword.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-064: If some other file is
# completely matched, a single <space> shall be inserted after the bigword.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-065: After this operation, sh
# shall be placed in insert mode.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-066: If at the end of the
# line, the current cursor position shall be moved to the first column position
# following the expansions and sh shall be placed in insert mode.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-067: Otherwise, the current
# cursor position shall be the last column position of the first character after
# the expansions and sh shall be placed in insert mode.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-068: If the current bigword
# contains none of the characters '?' , '*' , or '[' , before the operation, an
# <asterisk> ( '*' ) shall be implicitly assumed at the end.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-069: If the alias _letter
# contains other editing commands, these commands shall be performed as part of
# the insertion.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-070: If no alias _letter is
# enabled, this command shall have no effect.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-071: The current cursor
# position then shall be advanced by one character.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-072: If the cursor was
# positioned on the last character of the line, the case conversion shall occur,
# but the cursor shall not advance.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-073: If the '~' command is
# preceded by a count , that number of characters shall be converted, and the
# cursor shall be advanced to the character position after the last character
# converted.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-074: If the count is larger
# than the number of characters after the cursor, this shall not be considered
# an error; the cursor shall advance to the last character on the line.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-075: If the previous command
# was preceded by a count , and no count is given on the '.' command, the count
# from the previous command shall be included as part of the repeated command.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-076: If the '.' command is
# preceded by a count , this shall override any count argument to the previous
# command.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-077: The count specified in
# the '.' command shall become the count for subsequent '.' commands issued
# without a count.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-078: When the editor exits,
# the commands in the temporary file shall be executed and placed in the command
# history.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-079: If the cursor was
# positioned on the first character of the line, the terminal shall be alerted
# and the cursor shall not be moved.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-080: If the count is larger
# than the number of characters before the cursor, this shall not be considered
# an error; the cursor shall move to the first character on the line.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-081: If the cursor was
# positioned on the last character of the line, the terminal shall be alerted
# and the cursor shall not be advanced.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-082: If the count is larger
# than the number of words after the cursor, this shall not be considered an
# error; the cursor shall advance to the last character on the line.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-083: The cursor shall be moved
# to the end of the countth next word.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-084: If the count is larger
# than the number of bigwords after the cursor, this shall not be considered an
# error; the cursor shall advance to the last character on the line.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-085: The cursor shall be moved
# to the countth next occurrence of the character c.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-086: The cursor shall be moved
# to the countth previous occurrence of the character c.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-087: A non-interactive shell
# shall ignore this command.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-088: If there is no previous
# command, the terminal shall be alerted and the current command line...
# REQUIREMENT: SHALL-vi Line Editing Command Mode-089: If there is no next
# command, the terminal shall be alerted and the current command line...
# REQUIREMENT: SHALL-vi Line Editing Command Mode-090: If the count is larger
# than the number of words preceding the cursor, this shall not be considered an
# error; the cursor shall return to the first character on the line.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-091: If the line is empty, or
# the cursor is at the first character, the terminal shall be alerted.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-092: If the count is larger
# than the number of bigwords preceding the cursor, this shall not be considered
# an error; the cursor shall return to the first character on the line.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-093: The first character
# position shall be numbered 1.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-094: If the count is larger
# than the number of characters on the line, this shall not be considered an
# error; the cursor shall be placed on the last character on the line.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-095: If the countth previous
# command does not exist, the terminal shall be alerted and the current...
# REQUIREMENT: SHALL-vi Line Editing Command Mode-096: If the character 'c' does
# not occur in the line after the current cursor position, the terminal shall be
# alerted and the cursor shall not be moved.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-097: If the line is empty, or
# the cursor is at the last character, the terminal shall be alerted.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-098: If the character 'c' does
# not occur in the line before the current cursor position, the terminal shall
# be alerted and the cursor shall not be moved.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-099: If no f, F, t, or T
# command was previously performed, the terminal shall be alerted.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-100: Repeat the most recent f,
# F, t, or T command, looking for the previous occurrence of the character.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-101: If no f, F, t, or T
# command was previously performed, the terminal shall be alerted.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-102: Put the text buffer after
# the current character.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-103: Any number argument on
# that previous command shall be ignored.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-104: Replace the current
# character with the character c.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-105: Characters that are
# entered shall be inserted before the next character.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-106: Characters that are
# entered shall be inserted before the current character.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-107: If the motion command is
# the character 'c' , the current command line shall be cleared and insert mode
# shall be entered.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-108: If the motion command
# would move the current cursor position toward the beginning of the command
# line, the character under the current cursor position shall not be deleted.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-109: If the motion command
# would move the current cursor position toward the end of the command line, the
# character under the current cursor position shall be deleted.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-110: If the count is larger
# than the number of characters between the current cursor position and the end
# of the command line toward which the motion command would move the cursor,
# this shall not be considered an error; all of the remaining characters in the
# aforementioned range shall be deleted and insert mode shall be entered.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-111: If the motion command is
# invalid, the terminal shall be alerted, the cursor shall not be moved, and no
# text shall be deleted.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-112: After this command, the
# current cursor position shall be on the last character that was changed.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-113: If the count is larger
# than the number of characters after the cursor, this shall not be considered
# an error; all of the remaining characters shall be changed.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-114: If the cursor was
# positioned on the last character of the line, the character shall be deleted
# and the cursor position shall be moved to the previous character (the new last
# character).
# REQUIREMENT: SHALL-vi Line Editing Command Mode-115: If the count is larger
# than the number of characters after the cursor, this shall not be considered
# an error; all the characters from the cursor to the end of the line shall be
# deleted.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-116: The character under the
# current cursor position shall not change.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-117: If the cursor was
# positioned on the first character of the line, the terminal shall be alerted,
# and the X command shall have no effect.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-118: If the line contained a
# single character, the X command shall have no effect.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-119: If the line contained no
# characters, the terminal shall be alerted and the cursor shall not be moved.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-120: If the count is larger
# than the number of characters before the cursor, this shall not be considered
# an error; all the characters from before the cursor to the beginning of the
# line shall be deleted.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-121: The deleted characters
# shall be placed in the save buffer.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-122: The current character
# position shall be unchanged.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-123: The current cursor
# position shall be advanced to the last character put from the save buffer.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-124: A count shall indicate
# how many copies of the save buffer shall be put.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-125: The current cursor
# position shall be moved to the last character put from the save buffer.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-126: Search backward through
# the command history for the countth previous command comprising a string...
# REQUIREMENT: SHALL-vi Line Editing Command Mode-127: This operation shall not
# undo the copy of any command line to the edit line.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-128: All characters typed
# shall be appended to the search string, until a <newline> or <carriage-return>
# REQUIREMENT: SHALL-vi Line Editing Command Mode-129: If count is not
# specified, it shall default to 1.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-130: The cursor shall be
# positioned on the first character of the new command.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-131: If a k or - command would
# retreat past the maximum number of commands in effect for this shell (affected
# by the HISTSIZE environment variable), the terminal shall be alerted, and the
# command shall have no effect.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-132: If the cursor is already
# at the first character of the line, the terminal shall be alerted.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-133: Invert the case of the
# current character and advance the cursor one character.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-134: If a j or + command
# advances past the edit line, the current command line shall be restored to the
# edit line and the terminal shall be alerted.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-135: If command line number
# does not exist, the terminal shall be alerted and the command line shall not
# be changed.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-136: If this variable is
# unset, an unspecified default greater than or equal to 128 shall be used.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-137: If there is no previous
# non-empty pattern, the terminal shall be alerted and the current command line
# shall remain unchanged.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-138: If pattern is empty, the
# last non-empty pattern provided to / or ? shall be used.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-139: , the terminal shall be
# alerted and the current command line shall remain unchanged.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-140: If there is no previous /
# or ? , the terminal shall be alerted and the current command line shall remain
# unchanged.
# REQUIREMENT: SHALL-vi Line Editing Command Mode-141: If there is no previous /
# or ?, the terminal shall be alerted and the current command line shall rem...

report
