# Test: Word Expansions
# Target: tests/matrix/tests/word_expansions.sh
#
# Welcome to Word Expansions, the heart of the shell's processing engine! This
# suite ensures that everything from tildes to variable expansions, and
# arithmetic evaluation, transforms exactly as POSIX demands.

. "$MATRIX_DIR/lib.sh"

# ==============================================================================
# The Grand Order of Operations
# ==============================================================================
# REQUIREMENT: SHALL-2-6-101: The expansions that are performed for a given word
# shall be performed in the following order:
# REQUIREMENT: SHALL-2-6-102: Tilde expansion, parameter expansion, command
# substitution, and arithmetic expansion shall be performed...
# REQUIREMENT: SHALL-2-6-103: Field splitting shall be performed on the portions
# of the fields generated by step 1...
# REQUIREMENT: SHALL-2-6-104: Pathname expansion shall be performed, unless set
# -f is in effect.
# REQUIREMENT: SHALL-2-6-105: Quote removal, if performed, shall always be
# performed last.

# We test the entire sequence by constructing a word that relies on the correct
# order:
# 1. Parameter expansion happens first ($foo -> "~ *").
# 2. Field splitting occurs next (splitting "~" and "*").
# 3. Pathname expansion happens on the "*" (turning it into file names).
# 4. Quote removal removes the quotes on the original word (none in this case,
#    but we test quote removal separately).
# Note: Tilde expansion is NOT performed after parameter expansion.
touch file1 file2
test_cmd='foo="~ *"; printf "%s\n" $foo'
assert_stdout '~
file1
file2' \
    "$TARGET_SHELL -c '$test_cmd'"
rm file1 file2

# ==============================================================================
# The Magic of the Tilde
# ==============================================================================
# REQUIREMENT: SHALL-2-6-1-030: Tilde Expansion: A <tilde> ('~') character shall
# be subject to tilde expansion if it is the first character...
# REQUIREMENT: SHALL-2-6-1-113: If the tilde-prefix consists of only the <tilde>
# character, it shall be replaced by the value of the HOME variable.

# When a path starts with a lonely `~`, the shell is supposed to gracefully
# unfold it into the user's home directory. Let's make sure it knows the
# way home.
test_cmd='echo ~'
assert_stdout "$HOME" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-1-117: The pathname that replaces the tilde-prefix
# shall be treated as if quoted to prevent it being altered by later expansions.

# If `$HOME` contains a space or a wildcard, it should not be subjected to field
# splitting or pathname expansion. We test this by forcing `$HOME` to a string
# containing spaces and asterisks.
test_cmd='HOME="home with * spaces"; printf "%s\n" ~'
assert_stdout "home with * spaces" \
    "$TARGET_SHELL -c '$test_cmd'"


# ==============================================================================
# The Core Feature: Parameter Expansion
# ==============================================================================
# REQUIREMENT: SHALL-2-6-2-035: Parameter Expansion: The format for parameter
# expansion is as follows: ${expression}

# Braces provide the definitive boundaries for variables, preventing the shell
# from swallowing trailing characters into the variable name.
test_cmd='foo=hello; echo ${foo}'
assert_stdout "hello" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-2-036: Parameter Expansion: The <lbrace> and <rbrace>
# are required except when...

# But the shell is also forgiving; simple identifiers can skip the braces. We
# set `foo` and read it back raw.
test_cmd='foo=world; echo $foo'
assert_stdout "world" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-2-124: If parameter is unset or null, the expansion of
# word (or an empty string if word is omitted) shall be substituted. Otherwise,
# the value of parameter shall be substituted.
# [Use Default Values: ${parameter:-word}]

# We test `:-` fallback.
test_cmd='unset foo; echo "${foo:-default}"'
assert_stdout "default" \
    "$TARGET_SHELL -c '$test_cmd'"

test_cmd='foo=set; echo "${foo:-default}"'
assert_stdout "set" \
    "$TARGET_SHELL -c '$test_cmd'"

test_cmd='foo=""; echo "${foo:-default}"'
assert_stdout "default" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-2-125: If parameter is unset or null, quote removal
# shall be performed on the expansion of word and the result shall be assigned
# to parameter. In all cases, the final value of parameter shall be substituted.
# [Assign Default Values: ${parameter:=word}]

# We test `:=` assignment.
test_cmd='unset foo; echo "${foo:=assigned}"; echo "$foo"'
assert_stdout "assigned
assigned" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-2-126: If parameter is unset or null, the expansion of
# word (or a message indicating it is unset if word is omitted) shall be
# written to standard error and the shell exits with a non-zero exit status.
# [Indicate Error if Unset or Null: ${parameter:?word}]

# We test `:?` error generation.
test_cmd='unset foo; echo "${foo:?error message}"'
assert_stderr_contains "error message" \
    "$TARGET_SHELL -c '$test_cmd'"

assert_exit_code_non_zero \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-2-127: If parameter is unset or null, null shall be
# substituted. Otherwise, the expansion of word (or an empty string if word is
# omitted) shall be substituted. [Use Alternative Value: ${parameter:+word}]

# We test `:+` alternative value substitution.
test_cmd='unset foo; echo "${foo:+alt}"'
assert_stdout "" \
    "$TARGET_SHELL -c '$test_cmd'"

test_cmd='foo=set; echo "${foo:+alt}"'
assert_stdout "alt" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-2-128: The word shall be expanded to produce a pattern.
# The parameter expansion shall then result in parameter, with the smallest
# portion of the suffix matched by the pattern deleted.
# [Remove Smallest Suffix Pattern: ${parameter%word}]

test_cmd='foo="a.b.c"; echo "${foo%.*}"'
assert_stdout "a.b" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-2-129: The word shall be expanded to produce a pattern.
# The parameter expansion shall then result in parameter, with the largest
# portion of the suffix matched by the pattern deleted.
# [Remove Largest Suffix Pattern: ${parameter%%word}]

test_cmd='foo="a.b.c"; echo "${foo%%.*}"'
assert_stdout "a" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-2-130: The word shall be expanded to produce a pattern.
# The parameter expansion shall then result in parameter, with the smallest
# portion of the prefix matched by the pattern deleted.
# [Remove Smallest Prefix Pattern: ${parameter#word}]

test_cmd='foo="a.b.c"; echo "${foo#*.}"'
assert_stdout "b.c" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-2-131: The word shall be expanded to produce a pattern.
# The parameter expansion shall then result in parameter, with the largest
# portion of the prefix matched by the pattern deleted.
# [Remove Largest Prefix Pattern: ${parameter##word}]

test_cmd='foo="a.b.c"; echo "${foo##*.}"'
assert_stdout "c" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-2-132: The value of parameter shall be substituted.
# [String Length: ${#parameter}]

test_cmd='foo="hello"; echo "${#foo}"'
assert_stdout "5" \
    "$TARGET_SHELL -c '$test_cmd'"


# ==============================================================================
# Inception: Command Substitution
# ==============================================================================
# REQUIREMENT: SHALL-2-6-3-040: Command Substitution: Command substitution
# allows the output of a command to replace the command name...

# Command substitution is where the shell bends reality, executing a sub-command
# and inserting its stdout directly into the current command line. We test both
# the modern `$()` syntax and the classic backticks.
test_cmd_modern='echo $(echo success)'
assert_stdout "success" \
    "$TARGET_SHELL -c '$test_cmd_modern'"

test_cmd_classic='echo `echo success`'
assert_stdout "success" \
    "$TARGET_SHELL -c '$test_cmd_classic'"


# ==============================================================================
# Math Class: Arithmetic Expansion
# ==============================================================================
# REQUIREMENT: SHALL-2-6-4-045: Arithmetic Expansion: The format for arithmetic
# expansion shall be as follows: $((expression))

# POSIX shells double as calculators. By wrapping an expression in double
# parentheses, the shell evaluates the arithmetic and expands to the integer
# result.
test_cmd='echo $((2 + 2))'
assert_stdout "4" \
    "$TARGET_SHELL -c '$test_cmd'"


report
