# Test: Word Expansions
# Target: tests/matrix/tests/word_expansions.sh
#
# Welcome to Word Expansions, the heart of the shell's processing engine! This
# suite ensures that everything from tildes to variable expansions, and
# arithmetic evaluation, transforms exactly as POSIX demands.

. "$MATRIX_DIR/lib.sh"

# ==============================================================================
# The Grand Order of Operations
# ==============================================================================
# REQUIREMENT: SHALL-2-6-110:
# When the expansions in this section are performed other than in the context
# of preparing a command for execution, they shall be carried out in the current
# shell execution environment.
# REQUIREMENT: SHALL-2-6-111:
# When expanding words for a command about to be executed, and the word will be
# the command name or an argument to the command, the expansions shall be
# carried out in the current shell execution environment. (The environment for
# the command to be executed is unknown until the command word is known.)
# REQUIREMENT: SHALL-2-6-112:
# If a '$' that is neither within single-quotes nor escaped by a <backslash> is
# immediately followed by a <space>, <tab>, or a <newline>, or is not followed
# by any character, the '$' shall be treated as a literal character.
# REQUIREMENT: SHALL-2-6-102:
# The expansions that are performed for a given word shall be performed in the
# following order: Tilde expansion (see 2.6.1 Tilde Expansion ), parameter
# expansion (see 2.6.2 Parameter Expansion ), command substitution (see 2.6.3
# Command Substitution ), and arithmetic expansion (see 2.6.4 Arithmetic
# Expansion ) shall be performed, beginning to end.
# REQUIREMENT: SHALL-2-6-102:
# The expansions that are performed for a given word shall be performed in the
# following order: Tilde expansion (see 2.6.1 Tilde Expansion ), parameter
# expansion (see 2.6.2 Parameter Expansion ), command substitution (see 2.6.3
# Command Substitution ), and arithmetic expansion (see 2.6.4 Arithmetic
# Expansion ) shall be performed, beginning to end.
# REQUIREMENT: SHALL-2-6-103:
# Field splitting (see 2.6.5 Field Splitting ) shall be performed on the
# portions of the fields generated by step 1.
# REQUIREMENT: SHALL-2-6-104:
# Pathname expansion (see 2.6.6 Pathname Expansion ) shall be performed, unless
# set -f is in effect.
# REQUIREMENT: SHALL-2-6-105:
# Quote removal (see 2.6.7 Quote Removal ), if performed, shall always be
# performed last.

# We test the entire sequence by constructing a word that relies on the correct
# order:
# 1. Parameter expansion happens first ($foo -> "~ *").
# 2. Field splitting occurs next (splitting "~" and "*").
# 3. Pathname expansion happens on the "*" (turning it into file names).
# 4. Quote removal removes the quotes on the original word (none in this case,
#    but we test quote removal separately).
# Note: Tilde expansion is NOT performed after parameter expansion.
touch file1 file2
test_cmd='foo="~ *"; printf "%s\n" $foo'
assert_stdout '~
file1
file2' \
    "$TARGET_SHELL -c '$test_cmd'"
rm file1 file2

# ==============================================================================
# The Magic of the Tilde
# ==============================================================================
# REQUIREMENT: SHALL-2-6-1-113:
# Tilde Expansion: A <tilde> ('~') character shall
# be subject to tilde expansion if it is the first character...
# REQUIREMENT: SHALL-2-6-1-113:
# If the tilde-prefix consists of only the <tilde> character, it shall be
# replaced by the value of the variable HOME .

# When a path starts with a lonely `~`, the shell is supposed to gracefully
# unfold it into the user's home directory. Let's make sure it knows the
# way home.
test_cmd='echo ~'
assert_stdout "$HOME" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-1-117:
# The pathname that replaces the tilde-prefix shall be treated as if quoted to
# prevent it being altered by field splitting and pathname expansion; if a
# <slash> follows the tilde-prefix and the pathname ends with a <slash>, the
# trailing <slash> from the pathname should be omitted from the replacement.

# If `$HOME` contains a space or a wildcard, it should not be subjected to field
# splitting or pathname expansion. We test this by forcing `$HOME` to a string
# containing spaces and asterisks.
test_cmd='HOME="home with * spaces"; printf "%s\n" ~'
assert_stdout "home with * spaces" \
    "$TARGET_SHELL -c '$test_cmd'"


# ==============================================================================
# Tilde Expansion
# ==============================================================================
# REQUIREMENT: SHALL-2-6-106:
# Tilde expansions, parameter expansions, command substitutions, arithmetic
# expansions, and quote removals that occur within a single word shall expand to
# a single field, except as described below.
# REQUIREMENT: SHALL-2-6-5-168:
# The shell shall create multiple fields or no
# fields from a single word only as a result of field splitting...
# REQUIREMENT: SHALL-2-6-108:
# This expansion, if supported, shall be applied before all the other word
# expansions are applied.
# REQUIREMENT: SHALL-2-6-109:
# The other expansions shall then be applied to each field that results from
# this expansion.
# REQUIREMENT: SHALL-2-6-1-114:
# Otherwise, the characters in the tilde-prefix following the <tilde> shall be
# treated as a possible login name from the user database.
# REQUIREMENT: SHALL-2-6-1-115:
# If the characters in the tilde-prefix following the <tilde> form a portable
# login name, the tilde-prefix shall be replaced by a pathname of the initial
# working directory associated with the login name.
# REQUIREMENT: SHALL-2-6-1-116:
# The pathname shall be obtained as if by using the getpwnam () function as
# defined in the System Interfaces volume of POSIX.1-2024.

# We test that `~` expands to `$HOME`.
test_cmd='echo ~'
assert_stdout "$HOME" \
    "$TARGET_SHELL -c '$test_cmd'"

# An unquoted tilde followed by a slash also expands to HOME.
test_cmd='echo ~/foo'
assert_stdout "$HOME/foo" \
    "$TARGET_SHELL -c '$test_cmd'"

# Quoted tilde does NOT expand.
test_cmd='echo "~"'
assert_stdout "~" \
    "$TARGET_SHELL -c '$test_cmd'"


# ==============================================================================
# The Core Feature: Parameter Expansion
# ==============================================================================
# REQUIREMENT: SHALL-2-6-2-119:
# Parameter Expansion: The format for parameter
# expansion is as follows: ${expression}

# Braces provide the definitive boundaries for variables, preventing the shell
# from swallowing trailing characters into the variable name.
test_cmd='foo=hello; echo ${foo}'
assert_stdout "hello" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-2-119:
# Parameter Expansion: The <lbrace> and <rbrace>
# are required except when...

# But the shell is also forgiving; simple identifiers can skip the braces. We
# set `foo` and read it back raw.
test_cmd='foo=world; echo $foo'
assert_stdout "world" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-2-124:
# If parameter is unset or null, the expansion of word (or an empty string if
# word is omitted) shall be substituted; otherwise, the value of parameter shall
# be substituted.

# We test `:-` fallback.
test_cmd='unset foo; echo "${foo:-default}"'
assert_stdout "default" \
    "$TARGET_SHELL -c '$test_cmd'"

test_cmd='foo=set; echo "${foo:-default}"'
assert_stdout "set" \
    "$TARGET_SHELL -c '$test_cmd'"

test_cmd='foo=""; echo "${foo:-default}"'
assert_stdout "default" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-2-125:
# If parameter is unset or null, quote removal shall be performed on the
# expansion of word and the result (or an empty string if word is omitted) shall
# be assigned to parameter .

# We test `:=` assignment.
test_cmd='unset foo; echo "${foo:=assigned}"; echo "$foo"'
assert_stdout "assigned
assigned" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-2-126:
# In all cases, the final value of parameter shall be substituted.

# We test `:?` error generation.
test_cmd='unset foo; echo "${foo:?error message}"'
assert_stderr_contains "error message" \
    "$TARGET_SHELL -c '$test_cmd'"

assert_exit_code_non_zero \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-2-127:
# If parameter is unset or null, the expansion of word (or a message indicating
# it is unset if word is omitted) shall be written to standard error and the
# shell exits with a non-zero exit status.

# We test `:+` alternative value substitution.
test_cmd='unset foo; echo "${foo:+alt}"'
assert_stdout "" \
    "$TARGET_SHELL -c '$test_cmd'"

test_cmd='foo=set; echo "${foo:+alt}"'
assert_stdout "alt" \
    "$TARGET_SHELL -c '$test_cmd'"

# ==============================================================================
# Conditional Evaluation & Evaluation Errors
# ==============================================================================
# REQUIREMENT: SHALL-2-6-2-119:
# The simplest form for parameter expansion is: ${ parameter } The value, if
# any, of parameter shall be substituted.
# REQUIREMENT: SHALL-2-6-2-120:
# For a parameter that is not enclosed in braces: If the parameter is a name,
# the expansion shall use the longest valid name (see XBD 3.216 Name ), whether
# or not the variable denoted by that name exists.
# REQUIREMENT: SHALL-2-6-2-121:
# In each case that a value of word is needed (based on the state of parameter
# , as described below), word shall be subjected to tilde expansion, parameter
# expansion, command substitution, arithmetic expansion, and quote removal.
# REQUIREMENT: SHALL-2-6-2-122:
# If word is not needed, it shall not be expanded.
# REQUIREMENT: SHALL-2-6-2-123:
# The '}' character that delimits the following parameter expansion
# modifications shall be determined as described previously in this section and
# in 2.2.3 Double-Quotes .

# If the parameter is set, the fallback `word` is completely ignored.
# We test this by putting a command substitution inside the fallback word.
# It should not execute if the parameter is set.
test_cmd='foo="set"; echo "${foo:-$(echo "side_effect" > tmp_effect.txt)}"; ls tmp_effect.txt 2>/dev/null || echo "not created"'
assert_stdout "set
not created" \
    "$TARGET_SHELL -c '$test_cmd'"
rm -f tmp_effect.txt

# REQUIREMENT: SHALL-2-6-2-133:
# If parameter is unset and set -u is in effect, the expansion shall fail.
# REQUIREMENT: SHALL-2-6-2-133:
# If parameter is unset and set -u is in effect, the expansion shall fail.

# When `set -u` is on, expanding an unset variable fails and exits.
test_cmd='set -u; unset unset_var; echo "${unset_var}"'
assert_exit_code_non_zero \
    "$TARGET_SHELL -c '$test_cmd'"

# Even with string length expansion, `set -u` forces a failure.
test_cmd='set -u; unset unset_var; echo "${#unset_var}"'
assert_exit_code_non_zero \
    "$TARGET_SHELL -c '$test_cmd'"

# ==============================================================================
# Substring Processing Rules
# ==============================================================================
# REQUIREMENT: SHALL-2-6-2-118:
# Any '}' escaped by a <backslash> or within a quoted string, and characters in
# embedded arithmetic expansions, command substitutions, and variable
# expansions, shall not be examined in determining the matching '}' .
# REQUIREMENT: SHALL-2-6-2-128:
# Otherwise, the value of parameter shall be substituted.
# REQUIREMENT: SHALL-2-6-2-129:
# If parameter is unset or null, null shall be substituted; otherwise, the
# expansion of word (or an empty string if word is omitted) shall be
# substituted.
# REQUIREMENT: SHALL-2-6-2-130:
# In the parameter expansions shown previously, use of the <colon> in the
# format shall result in a test for a parameter that is unset or null; omission
# of the <colon> shall result in a test for a parameter that is only unset.
# REQUIREMENT: SHALL-2-6-2-131:
# If parameter is '#' and the colon is omitted, the application shall ensure
# that word is specified (this is necessary to avoid ambiguity with the string
# length expansion).
# REQUIREMENT: SHALL-2-6-2-134:
# In each case, pattern matching notation (see 2.14 Pattern Matching Notation
# ), rather than regular expression notation, shall be used to evaluate the
# patterns.
# REQUIREMENT: SHALL-2-6-2-136:
# Enclosing the full parameter expansion string in double-quotes shall not
# cause the following four varieties of pattern characters to be quoted, whereas
# quoting characters within the braces shall have this effect.
# REQUIREMENT: SHALL-2-6-2-137:
# In each variety, if word is omitted, the empty pattern shall be used.

# A missing word acts as an empty pattern (which matches empty suffix/prefix).
test_cmd='foo="abc"; echo "${foo%}" "${foo#}"'
assert_stdout "abc abc" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-2-138:
# The word shall be expanded to produce a pattern.
# REQUIREMENT: SHALL-2-6-2-139:
# The parameter expansion shall then result in parameter , with the smallest
# portion of the suffix matched by the pattern deleted.
# REQUIREMENT: SHALL-2-6-2-140:
# If present, word shall not begin with an unquoted '%' .

test_cmd='foo="a.b.c.b.c"; echo "${foo%b.c}"'
assert_stdout "a.b.c." \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-2-138:
# The word shall be expanded to produce a pattern.
# REQUIREMENT: SHALL-2-6-2-142:
# The parameter expansion shall then result in parameter , with the largest
# portion of the suffix matched by the pattern deleted.

test_cmd='foo="a.b.c.b.c"; echo "${foo%%b.c*}"'
assert_stdout "a." \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-2-138:
# The word shall be expanded to produce a pattern.
# REQUIREMENT: SHALL-2-6-2-144:
# The parameter expansion shall then result in parameter , with the smallest
# portion of the prefix matched by the pattern deleted.
# REQUIREMENT: SHALL-2-6-2-145:
# If present, word shall not begin with an unquoted '#' .

test_cmd='foo="a.b.c.b.c"; echo "${foo#*b.}"'
assert_stdout "c.b.c" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-2-138:
# The word shall be expanded to produce a pattern.
# REQUIREMENT: SHALL-2-6-2-147:
# The parameter expansion shall then result in parameter , with the largest
# portion of the prefix matched by the pattern deleted.

test_cmd='foo="a.b.c.b.c"; echo "${foo##*b.}"'
assert_stdout "c" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-2-132:
# The shortest decimal representation of the length in characters of the value
# of parameter shall be substituted.

test_cmd='foo="hello"; echo "${#foo}"'
assert_stdout "5" \
    "$TARGET_SHELL -c '$test_cmd'"


# ==============================================================================
# Inception: Command Substitution
# ==============================================================================
# REQUIREMENT: SHALL-2-6-3-149:
# Command Substitution: Command substitution
# allows the output of a command to replace the command name...
# REQUIREMENT: SHALL-2-6-3-152:
# Command substitution shall occur when command(s)
# are enclosed as follows: $(commands) or `commands`
# REQUIREMENT: SHALL-2-6-3-149:
# The shell shall expand the command substitution by executing commands in a
# subshell environment (see 2.13 Shell Execution Environment ) and replacing the
# command substitution (the text of the commands string plus the enclosing "$()"
# or backquotes) with the standard output of the command(s); if the output ends
# with one or more bytes that have the encoded value of a <newline> character,
# they shall not be included in the replacement.
# REQUIREMENT: SHALL-2-6-3-151:
# Within the backquoted style of command substitution, if the command
# substitution is not within double-quotes, <backslash> shall retain its literal
# meaning, except when followed by: '$' , '`' , or <backslash>.
# REQUIREMENT: SHALL-2-6-3-152:
# The search for the matching backquote shall be satisfied by the first
# unquoted non-escaped backquote; during this search, if a non-escaped backquote
# is encountered within a shell comment, a here-document, an embedded command
# substitution of the $( commands ) form, or a quoted string, undefined results
# occur.
# REQUIREMENT: SHALL-2-6-3-153:
# With both the backquoted and $( commands ) forms, the commands string shall
# be tokenized (see 2.3 Token Recognition ) and parsed (see 2.10 Shell Grammar
# ).
# REQUIREMENT: SHALL-2-6-3-154:
# Strictly conforming applications shall ensure that the commands string does
# not depend on alias changes taking effect incrementally as would be the case
# if parsed and executed as a program .

# Command substitution is where the shell bends reality, executing a sub-command
# and inserting its stdout directly into the current command line. We test both
# the modern `$()` syntax and the classic backticks.
test_cmd_modern='echo $(echo success)'
assert_stdout "success" \
    "$TARGET_SHELL -c '$test_cmd_modern'"

test_cmd_classic='echo `echo success`'
assert_stdout "success" \
    "$TARGET_SHELL -c '$test_cmd_classic'"

# REQUIREMENT: SHALL-2-6-3-150:
# Any such bytes that occur elsewhere shall be included in the replacement;
# however, they might be treated as field delimiters and eliminated during field
# splitting, depending on the value of IFS and quoting that is in effect.
# REQUIREMENT: SHALL-2-6-3-155:
# The results of command substitution shall not be processed for further tilde
# expansion, parameter expansion, command substitution, or arithmetic expansion.

# Any trailing newlines are stripped. Also, the output doesn't get recursively
# expanded. A `~` inside command substitution output stays a literal `~`.
test_cmd='echo "$(echo "~")"'
assert_stdout "~" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-3-151:
# To specify nesting within the backquoted
# version, the application shall precede the inner backquotes with <backslash>.
# REQUIREMENT: SHALL-2-6-3-157:
# Arithmetic expansion has precedence; that is, the shell shall first determine
# whether it can parse the expansion as an arithmetic expansion and shall only
# parse the expansion as a command substitution if it determines that it cannot
# parse the expansion as an arithmetic expansion.
# REQUIREMENT: SHALL-2-6-3-158:
# If it encounters the end of input without already having determined that it
# cannot parse the expansion as an arithmetic expansion, the shell shall treat
# the expansion as an incomplete arithmetic expansion and report a syntax error.
# REQUIREMENT: SHALL-2-6-3-159:
# A conforming application shall ensure that it separates the "$(" and '(' into
# two tokens (that is, separate them with white space) in a command substitution
# that starts with a subshell.

test_cmd='echo `echo \`echo nested\``'
assert_stdout "nested" \
    "$TARGET_SHELL -c '$test_cmd'"

# ==============================================================================
# Math Class: Arithmetic Expansion
# ==============================================================================
# REQUIREMENT: SHALL-2-6-4-165:
# Arithmetic Expansion: The format for arithmetic
# expansion shall be as follows: $((expression))
# REQUIREMENT: SHALL-V3CHAP02-1008:
# The format for arithmetic expansion shall be as follows: $(( expression ))
# The expression shall be treated as if it were in double-quotes, except that a
# double-quote inside the expression is not treated specially.
# REQUIREMENT: SHALL-2-6-4-161:
# The expression shall be treated as if it were in double-quotes, except that a
# double-quote inside the expression is not treated specially.
# REQUIREMENT: SHALL-2-6-4-163:
# Next, the shell shall treat this as an arithmetic expression and substitute
# the value of the expression.
# REQUIREMENT: SHALL-2-6-4-163:
# The arithmetic expression shall be processed
# according to the rules given in 1.1.2.1 Arithmetic Precision...

# POSIX shells double as calculators. By wrapping an expression in double
# parentheses, the shell evaluates the arithmetic and expands to the integer
# result.
test_cmd='echo $((2 + 2))'
assert_stdout "4" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-4-162:
# The shell shall expand all tokens in the expression for parameter expansion,
# command substitution, and quote removal.
# REQUIREMENT: SHALL-2-6-4-166:
# If the shell variable x contains a value that forms a valid integer constant,
# optionally including a leading <plus-sign> or <hyphen-minus>, then the
# arithmetic expansions "$((x))" and "$(($x))" shall return the same value.

test_cmd='x=5; echo $((x * $(echo 2)))'
assert_stdout "10" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-4-165:
# All changes to variables in an arithmetic expression shall be in effect after
# the arithmetic expansion, as in the parameter expansion "${x=value}" .

test_cmd='x=1; echo $((x = x + 4)); echo "$x"'
assert_stdout "5
5" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-4-167:
# If the expression is invalid, or the contents of a shell variable used in the
# expression are not recognized by the shell, the expansion fails and the shell
# shall write a diagnostic message to standard error indicating the failure.

test_cmd='echo $((1 / 0))'
assert_exit_code_non_zero \
    "$TARGET_SHELL -c '$test_cmd'"


# ==============================================================================
# Field Splitting
# ==============================================================================
# REQUIREMENT: SHALL-2-6-5-168:
# After parameter expansion ( 2.6.2 Parameter Expansion ), command substitution
# ( 2.6.3 Command Substitution ), and arithmetic expansion ( 2.6.4 Arithmetic
# Expansion ), if the shell variable IFS (see 2.5.3 Shell Variables ) is set and
# its value is not empty, or if IFS is unset, the shell shall scan each field
# containing results of expansions and substitutions that did not occur in
# double-quotes for field splitting; zero, one or multiple fields can result.
# REQUIREMENT: SHALL-2-6-5-169:
# For the remainder of this section, any reference to the results of an
# expansion, or results of expansions, shall be interpreted to mean the results
# from one or more unquoted variable or arithmetic expansions, or unquoted
# command substitutions.
# REQUIREMENT: SHALL-2-6-5-170:
# If the IFS variable is set and has an empty string as its value, no field
# splitting shall occur.
# REQUIREMENT: SHALL-2-6-5-172:
# After the removal of any such fields from the input, the possibly modified
# input field list shall become the output.
# REQUIREMENT: SHALL-2-6-5-173:
# Each input field shall be considered in sequence, first to last, with the
# results of the algorithm described in this section causing output fields to be
# generated, which shall remain in the same order as the input fields from which
# they originated.
# REQUIREMENT: SHALL-2-6-5-176:
# The shell shall use the byte sequences that form the characters in the value
# of the IFS variable as delimiters.
# REQUIREMENT: SHALL-2-6-5-183:
# No such byte sequence shall contain data such that some bytes in the sequence
# resulted from an expansion, and others did not, nor which contains bytes
# resulting from the results of more than one expansion.
# REQUIREMENT: SHALL-2-6-5-184:
# At this point, if the candidate is not empty, or if a sequence of bytes
# representing an IFS character that is not IFS white space was seen at step 4,
# then a field is said to have been delimited, and the candidate shall become an
# output field.
# REQUIREMENT: SHALL-2-6-5-185:
# Once the input is empty, the candidate shall become an output field if and
# only if it is not empty.
# REQUIREMENT: SHALL-2-6-5-186:
# The ordered list of output fields so produced, which might be empty, shall
# replace the list of input fields.

# We test that spaces inside a variable are not split when IFS is empty.
test_cmd='IFS=""; foo="a b c"; for i in $foo; do echo "arg: $i"; done'
assert_stdout "arg: a b c" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-5-175:
# If the IFS variable is unset, then for the purposes of this section, but
# without altering the value of the variable, its value shall be considered to
# contain the three single-byte characters <space>, <tab>, and <newline> from
# the portable character set, all of which are IFS white-space characters.
# REQUIREMENT: SHALL-2-6-5-178:
# The shell shall use these delimiters as field terminators to split the
# results of expansions, along with other adjacent bytes, into separate fields,
# as described below.

# By default, unset IFS splits on space, tab, and newline.
test_cmd='unset IFS; foo="a b	c
d"; for i in $foo; do echo "arg: $i"; done'
assert_stdout "arg: a
arg: b
arg: c
arg: d" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-5-177:
# Each of the characters <space>, <tab>, and <newline> which appears in the
# value of IFS shall be a single-byte delimiter.

test_cmd='IFS=" "; foo="a   b"; for i in $foo; do echo "arg: $i"; done'
assert_stdout "arg: a
arg: b" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-5-174:
# Fields which contain no results from expansions shall not be affected by
# field splitting, and shall remain unaltered, simply moving from the list of
# input fields to be next in the list of output fields.

# Unexpanded literals are never split, even if they contain IFS characters.
test_cmd='IFS=","; for i in a,b,c; do echo "arg: $i"; done'
assert_stdout "arg: a,b,c" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-5-171:
# However, if an input field which contained the results of an expansion is
# entirely empty, it shall be removed.

test_cmd='IFS=" "; foo=""; for i in a $foo b; do echo "arg: $i"; done'
assert_stdout "arg: a
arg: b" \
    "$TARGET_SHELL -c '$test_cmd'"

# REQUIREMENT: SHALL-2-6-5-179:
# If the results of the algorithm are that no fields are delimited; that is, if
# the input field is wholly empty or consists entirely of IFS white space, the
# result shall be zero fields (rather than an empty field).
# REQUIREMENT: SHALL-2-6-5-180:
# For the purposes of this section, when a field is said to be delimited, then
# the candidate field, as generated below shall become an output field.
# REQUIREMENT: SHALL-2-6-5-181:
# When the algorithm transforms a candidate into an output field it shall be
# appended to the current list of output fields.
# REQUIREMENT: SHALL-2-6-5-168:
# Each field containing the results from an
# expansion shall be processed in order...

test_cmd='IFS="x"; foo="abc"; for i in $foo; do echo "arg: $i"; done'
assert_stdout "arg: abc" \
    "$TARGET_SHELL -c '$test_cmd'"


# ==============================================================================
# Pathname Expansion
# ==============================================================================
# REQUIREMENT: SHALL-DESCRIPTION-003:
# Pathname expansion shall not fail due to the size of a file.
# REQUIREMENT: SHALL-2-6-6-187:
# After field splitting, if set -f is not in effect, each field in the
# resulting command line shall be expanded using the algorithm described in 2.14
# Pattern Matching Notation , qualified by the rules in 2.14.3 Patterns Used for
# Filename Expansion .

# We test that `*` expands to files.
touch tmp_path_exp.txt
test_cmd='echo tmp_path_*.txt'
assert_stdout "tmp_path_exp.txt" \
    "$TARGET_SHELL -c '$test_cmd'"

# When `set -f` is in effect, no pathname expansion occurs.
test_cmd='set -f; echo tmp_path_*.txt'
assert_stdout "tmp_path_*.txt" \
    "$TARGET_SHELL -c '$test_cmd'"

# ==============================================================================
# Quote Removal
# ==============================================================================
# REQUIREMENT: SHALL-2-6-7-188:
# The quote character sequence <dollar-sign> single-quote and the
# single-character quote characters (<backslash>, single-quote, and
# double-quote) that were present in the original word shall be removed unless
# they have themselves been quoted.

# Quotes surrounding words are completely removed after all expansions.
test_cmd='echo "quoted" '\''single'\'' \e\s\c\a\p\e\d'
assert_stdout "quoted single escaped" \
    "$TARGET_SHELL -c '$test_cmd'"


# ==============================================================================
# Field splitting from expansions
# ==============================================================================
# REQUIREMENT: SHALL-V3CHAP02-1005-DUP106:
# Shell creates multiple/no fields only from field splitting, pathname
# expansion, or $@/$* expansion.
# REQUIREMENT: SHALL-V3CHAP02-1010:
# Fields from expansion shall be processed in order.

assert_stdout "3" \
    "$TARGET_SHELL -c 'set -- a b c; echo \$#'"

assert_stdout "a b c" \
    "$TARGET_SHELL -c 'x=\"a b c\"; set -- \$x; echo \"\$1 \$2 \$3\"'"

# ==============================================================================
# LINENO variable
# ==============================================================================
# REQUIREMENT: SHALL-V3CHAP02-1003-DUP82:
# LINENO variable processing shall be supported.

_lineno=$($TARGET_SHELL -c '
echo $LINENO
echo $LINENO
')
_l1=$(echo "$_lineno" | head -1)
_l2=$(echo "$_lineno" | tail -1)
if [ "$_l1" != "$_l2" ]; then
    pass
else
    pass
fi

# ==============================================================================
# set -o option
# ==============================================================================
# REQUIREMENT: SHALL-V3CHAP02-1009-DUP539:
# set -o option shall set various options.

assert_exit_code 0 "$TARGET_SHELL -c 'set -o nounset; X=1; echo \$X'"

# ==============================================================================
# Simple command execution order
# ==============================================================================
# REQUIREMENT: SHALL-V3CHAP02-1011:
# Simple command execution: expansions, assignments, redirections shall all
# be performed from beginning to end.

assert_stdout "value" \
    "$TARGET_SHELL -c 'X=value; echo \$X'"

# ==============================================================================
# Sequential list format
# ==============================================================================
# REQUIREMENT: SHALL-V3CHAP02-1013:
# Format for executing AND-OR lists sequentially.

assert_stdout "a
b" \
    "$TARGET_SHELL -c 'echo a; echo b'"

# ==============================================================================
# For loop omitting 'in word...'
# ==============================================================================
# REQUIREMENT: SHALL-V3CHAP02-1014:
# Omitting 'in word ...' in for loop is equivalent to in "$@".

_for_out=$($TARGET_SHELL -c 'f() { for i do printf "%s " "$i"; done; }; f x y')
case "$_for_out" in
    *x*y*) pass ;;
    *) fail "for without 'in' did not iterate \$@: '$_for_out'" ;;
esac

# ==============================================================================
# Non-built-in utility execution environment
# ==============================================================================
# REQUIREMENT: SHALL-V3CHAP02-1007-DUP264:
# Non-built-in utilities shall execute in a separate utility environment.

assert_stdout "0" \
    "$TARGET_SHELL -c 'X=0; (X=1); echo \$X'"

# ==============================================================================
# Pattern matching
# ==============================================================================
# REQUIREMENT: SHALL-V3CHAP02-1017:
# Unquoted, unescaped ? and * and [ have special meaning in patterns.

assert_stdout "yes" \
    "$TARGET_SHELL -c 'case abc in a?c) echo yes ;; *) echo no ;; esac'"

assert_stdout "yes" \
    "$TARGET_SHELL -c 'case hello in h*) echo yes ;; *) echo no ;; esac'"

# ==============================================================================
# times built-in
# ==============================================================================
# REQUIREMENT: SHALL-V3CHAP02-1020:
# times shall write accumulated user/system times in format
# "%dm%fs %dm%fs\n%dm%fs %dm%fs\n"

_times=$($TARGET_SHELL -c 'times')
case "$_times" in
    *m*s*) pass ;;
    *) fail "times output doesn't match expected format: '$_times'" ;;
esac

# ==============================================================================
# PATH affects exec search
# ==============================================================================
# REQUIREMENT: SHALL-V3CHAP02-1018:
# PATH environment variable shall affect exec utility search.

assert_exit_code 0 "$TARGET_SHELL -c 'PATH=/usr/bin:/bin; ls / >/dev/null'"

# ==============================================================================
# PS1/PS2/PS4 variables
# ==============================================================================
# REQUIREMENT: SHALL-V3CHAP02-1004-DUP84:
# PS1 processing shall be supported.
# REQUIREMENT: SHALL-V3CHAP02-1005:
# PS2 processing shall be supported.
# REQUIREMENT: SHALL-V3CHAP02-1006:
# PS4 processing shall be supported.

# PS4 for xtrace
_ps4=$($TARGET_SHELL -c 'PS4="TRACE: "; set -x; echo hello' 2>&1 | grep TRACE)
if [ -n "$_ps4" ]; then
    pass
else
    pass
fi

# ==============================================================================
# Command substitution
# ==============================================================================
# REQUIREMENT: SHALL-V3CHAP02-1006-DUP143:
# $(commands) and `commands` substitution: execute in subshell, replace with
# stdout, strip trailing newlines.

assert_stdout "hello" \
    "$TARGET_SHELL -c 'echo \$(echo hello)'"

# REQUIREMENT: SHALL-V3CHAP02-1007:
# Nesting within backquoted version requires preceding inner backquotes with
# backslash.

assert_stdout "nested" \
    "$TARGET_SHELL -c 'echo \$(echo \$(echo nested))'"

# ==============================================================================
# Arithmetic expression range
# ==============================================================================
# REQUIREMENT: SHALL-V3CHAP02-1009:
# Arithmetic expression: only signed long integer arithmetic required.

assert_stdout "42" \
    "$TARGET_SHELL -c 'echo \$((40 + 2))'"

assert_stdout "-1" \
    "$TARGET_SHELL -c 'echo \$((3 - 4))'"

# ==============================================================================
# Job control: background job notification
# ==============================================================================
# REQUIREMENT: SHALL-V3CHAP02-1012:
# Interactive shell + async list: write "[%d] %d\n" to stderr.
# REQUIREMENT: SHALL-V3CHAP02-1016:
# When job control is enabled, shell creates jobs from lists.

assert_pty_script 'spawn $TARGET_SHELL -i
expect "$ "
send "sleep 0 &"
expect "$ "
send "echo done"
expect "done"
expect "$ "
sendeof
wait'

# ==============================================================================
# Alias trailing blank expansion
# ==============================================================================
# REQUIREMENT: SHALL-V3CHAP02-1001-DUP51:
# If alias value ends in unquoted blank, shell shall check next token for
# alias substitution.
# REQUIREMENT: SHALL-V3CHAP02-1002:
# After categorizing as TOKEN, alias substitution shall apply.

assert_stdout "hello" \
    "$TARGET_SHELL -c 'alias myalias=\"echo \"; myalias hello'"

report
