# SHALL-20-100-03-010
# "The specified var operands shall be processed in the order they appear on
#  the command line, and the output fields generated by the field splitting
#  algorithm shall be used in the order they were generated"
# Verifies: variables are assigned fields left-to-right in order.

unset IFS
printf 'alpha beta gamma\n' | {
  read x y z
  if [ "$x" != "alpha" ] || [ "$y" != "beta" ] || [ "$z" != "gamma" ]; then
    printf '%s\n' "FAIL: x='$x' y='$y' z='$z'" >&2; exit 1
  fi
}
[ $? -ne 0 ] && exit 1

exit 0
