# SHALL-19-06-003
# "Field splitting shall be performed on the portions of the fields generated by
#  step 1."
# Verify field splitting occurs on expansion results.

fail=0

# Unquoted expansion result is field-split
x="a b c"
set -- $x
[ $# -eq 3 ] || { printf '%s\n' "FAIL: field split count = $#, expected 3" >&2; fail=1; }

# Quoted expansion result is NOT field-split
set -- "$x"
[ $# -eq 1 ] || { printf '%s\n' "FAIL: quoted no-split count = $#, expected 1" >&2; fail=1; }

# Literal text is not split even with spaces
set -- "a b c"
[ $# -eq 1 ] || { printf '%s\n' "FAIL: literal quoted count = $#, expected 1" >&2; fail=1; }

# IFS-based splitting
IFS=:
x="a:b:c"
set -- $x
[ $# -eq 3 ] || { printf '%s\n' "FAIL: IFS=: split count = $#, expected 3" >&2; fail=1; }
unset IFS

exit "$fail"
